### ISSUE TITLE
get stuck in Inplace_abn

### ISSUE THREAD

**Issue by tjulyz** [PkuRainBow/OCNet#31]
**When I training to train the net, it gets stuck in Inplace abn.
I have tried to build some new environment by conda or using the python of system.
They don't work! There is not any error information until I stop the program.
Any Solution? 
Thank you!
Using python3.6 cuda9.0 pytorch 0.4.1**
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    main()
  File "train.py", line 168, in main
    preds = model(images)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 71, in parallel_apply
    _worker(0, modules[0], inputs[0], kwargs_tup[0], devices[0])
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/OCNet/network/resnet101_baseline.py", line 89, in forward
Process Process-1:
    **x = self.relu1(self.bn1(self.conv1(x)))**
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/OCNet/utils/../inplace_abn/bn.py", line 169, in forward
    extra, self.training, self.momentum, self.eps, self.activation, self.slope)
  File "/home/ubuntu/OCNet/utils/../inplace_abn/functions.py", line 163, in forward
    mean_w, var_w = ctx.master_queue.get()
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 96, in _worker_loop
    r = index_queue.get(timeout=MANAGER_STATUS_CHECK_INTERVAL)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/ubuntu/anaconda2/envs/torch/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)

**Comment by h982639009** [comment]
@tjulyz Hi, have you got any solutions to this problem? I met the same problem with you.

**Comment by kfxw** [comment]
I came up with the same issue.
I used the docker images provided by the author, but the sync bn still got stuck at self.bn1()
Then I replaced the sync bn with [this one from CSAIL](https://github.com/CSAILVision/semantic-segmentation-pytorch/tree/master/lib/nn/modules), it began to run. However, I haven't compared the differences on performance yet.
